name: Compilation

on: workflow_dispatch

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: compile 3proxy with Visual C++
      run: nmake /f Makefile.msvc64

    - uses: actions/upload-artifact@v3
      with:
        path: ${{github.workspace}}
