name: Compilation

on: workflow_dispatch

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: compile 3proxy (x64) with Visual C++
      run: |
        CALL "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        SET "PATH=C:\Program Files\OpenSSL\bin;%PATH%"
        SET "INCLUDE=C:\Program Files\OpenSSL\include;%INCLUDE%"
        SET "LIB=C:\Program Files\OpenSSL\lib;%LIB%"
        REM SET "LIB=C:\Program Files\OpenSSL\lib\VC;%LIB%"
        SET "LIB=C:\Program Files\OpenSSL\lib\VC\static;%LIB%"
        NMAKE /F Makefile.msvc64
      shell: CMD

    - uses: actions/upload-artifact@v3
      with:
        path: ${{github.workspace}}
