name: Compilation

on: workflow_dispatch

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: compile 3proxy with Visual C++
      run: |
        TYPE "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        CALL "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        nmake /f Makefile.msvc64
      shell: CMD

    - uses: actions/upload-artifact@v3
      with:
        path: ${{github.workspace}}
